server:
  port: 8072

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: advertise-service
          uri: lb://advertise-service
          predicates:
            - Path=/advertise/**
          filters:
            - RewritePath=/advertise/(?<path>.*), /$\{path}
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**
          filters:
            - RewritePath=/report/(?<path>.*), /$\{path}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"